version: '3'
services:
  shopeed-frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "4200:80"
  shopeed-backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "5000:5000"